version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
  kibana:
    build: ./kibana
    depends_on: 
      - "elasticsearch"
    ports:
      - "5601:5601"